### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by mhf-ir** [daniel-e/rust-captcha#2]
Is there any benchmark ?
How many captcha / seconds ?

**Comment by daniel-e** [comment]
I have added a very simply benchmark to the testing/ directory.

When running one instance in a docker container with 8 clients on the same machine I can achieve 500 CAPTCHAs/sec on a i7-4790 @ 3.60GHz.

To reproduce it first start the instance:
cd docker
make build
make run

In another console:
cd testing
./test.py 8

**Comment by mhf-ir** [comment]
awesome, most use case of captcha is prevent bot attempts and (d)dos protection.
So captcha itself also could be problem,
Rust and faster benchmark and minimal resource usage will be awesome, thank to your package.
Thank you some much.
I think minimal script to run benchmark to run by our hardware would be great.
